"""cards table

Revision ID: 9560a354e3f6
Revises: 3c9c8e181e33
Create Date: 2020-10-01 23:25:44.120442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9560a354e3f6'
down_revision = '3c9c8e181e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('front', sa.String(length=300), nullable=True),
    sa.Column('back', sa.String(length=1000), nullable=True),
    sa.Column('known', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_timestamp'), 'card', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_timestamp'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
